// <auto-generated />
namespace Webtag.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201512281948418_AddLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
