// <auto-generated />
namespace Webtag.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddWidgets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWidgets));
        
        string IMigrationMetadata.Id
        {
            get { return "201512292300373_AddWidgets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
